# Generated by Django 5.1.1 on 2025-10-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmate',
            options={},
        ),
        migrations.RemoveField(
            model_name='inmate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='inmate',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.TextField()),
                ('bond_amount', models.CharField(blank=True, max_length=50)),
                ('court_case_number', models.CharField(blank=True, max_length=50)),
                ('court_location', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='core.inmate')),
            ],
        ),
        migrations.DeleteModel(
            name='Play',
        ),
    ]
