# Generated by Django 5.1.1 on 2025-10-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_inmate_options_remove_inmate_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAbuseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inmate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idx_child_abuse', to='core.inmate')),
            ],
        ),
        migrations.CreateModel(
            name='NonChildAbuseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inmate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idx_non_child_abuse', to='core.inmate')),
            ],
        ),
    ]
