# Generated by Django 5.1.1 on 2025-10-02 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leaderboardentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MurderIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inmate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idx_murder', to='core.inmate')),
            ],
        ),
        migrations.CreateModel(
            name='NonMurderIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inmate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idx_non_murder', to='core.inmate')),
            ],
        ),
    ]
