# Generated by Django 5.1.1 on 2025-10-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_murderindex_nonmurderindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='mode',
            field=models.CharField(choices=[('child', 'Child vs Non-Child'), ('murder', 'Murder vs Non-Murder')], db_index=True, default=0, max_length=12),
            preserve_default=False,
        ),
    ]
