# Generated by Django 5.1.1 on 2025-10-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leaderboardentry_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='mode',
            field=models.CharField(choices=[('child', 'Child Abuse'), ('murder', 'Murder')], max_length=20),
        ),
    ]
