# Generated by Django 5.1.1 on 2025-10-03 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_leaderboardentry_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='mode',
            field=models.CharField(choices=[('child', 'Child Abuse'), ('murder', 'Murder'), ('drugs', 'Drugs')], max_length=20),
        ),
        migrations.CreateModel(
            name='CannabisIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idx_cannabis', to='core.inmate')),
            ],
        ),
        migrations.CreateModel(
            name='CocaineFentanylIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idx_cocaine_fentanyl', to='core.inmate')),
            ],
        ),
    ]
