# Generated by Django 5.1.1 on 2025-10-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_leaderboardentry_mode_cannabisindex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmate',
            name='image',
        ),
    ]
